DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS user;


CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);


CREATE TABLE message (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	msg TEXT NOT NULL,
	sender INTEGER NOT NULL,
	time_sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (sender) REFERENCES user (id)
);