DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);


CREATE TABLE messages (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	msg TEXT NOT NULL,
	sender TEXT NOT NULL,
	time_sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (sender) REFERENCES users (username)
);