DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS users;



CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	profile_img_url TEXT,
	isOnline BIT
);


CREATE TABLE messages (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	msg TEXT NOT NULL,
	sender_id INTEGER NOT NULL,
	time_sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	belongs_to INTEGER, 
	FOREIGN KEY (sender_id) REFERENCES users(id),
	FOREIGN KEY (belongs_to) REFERENCES chats (id)
);

CREATE TABLE chats (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	receiver_id INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES users (id),
	FOREIGN KEY (receiver_id) REFERENCES users (id)
);